local map = vim.keymap.set

map("n", "<leader>kl", "<cmd>Lazy<cr>", { desc = "Lazy" })
map("n", "<leader>km", "<cmd>Mason<cr>", { desc = "Mason" })
map("n", "<leader>kc", "<cmd>VenvSelect<cr>", { desc = "Select Virtualenv" })

map({ "i", "x", "n", "s" }, "<C-s>", "<cmd>w<cr><esc>", { desc = "Save File" })

map("v", "<", "<gv")
map("v", ">", ">gv")

map("n", "<leader>bs", "<cmd>w<cr>", { desc = "Save Buffer" })

map("n", "<C-h>", "<C-w>h", { desc = "Go to Left Window", remap = true })
map("n", "<C-j>", "<C-w>j", { desc = "Go to Lower Window", remap = true })
map("n", "<C-k>", "<C-w>k", { desc = "Go to Upper Window", remap = true })
map("n", "<C-l>", "<C-w>l", { desc = "Go to Right Window", remap = true })

map("n", "<C-Up>", "<cmd>resize +2<cr>", { desc = "Increase Window Height" })
map("n", "<C-Down>", "<cmd>resize -2<cr>", { desc = "Decrease Window Height" })
map("n", "<C-Left>", "<cmd>vertical resize -2<cr>", { desc = "Decrease Window Width" })
map("n", "<C-Right>", "<cmd>vertical resize +2<cr>", { desc = "Increase Window Width" })

map("n", "<A-j>", "<cmd>m .+1<cr>==", { desc = "Move Down" })
map("n", "<A-k>", "<cmd>m .-2<cr>==", { desc = "Move Up" })
map("i", "<A-j>", "<esc><cmd>m .+1<cr>==gi", { desc = "Move Down" })
map("i", "<A-k>", "<esc><cmd>m .-2<cr>==gi", { desc = "Move Up" })
map("v", "<A-j>", ":m '>+1<cr>gv=gv", { desc = "Move Down" })
map("v", "<A-k>", ":m '<-2<cr>gv=gv", { desc = "Move Up" })

map("n", "<leader>cS", "<cmd>:%s/\\t/  /g<cr>", { desc = "Convert all tabs into spaces" })
map("n", "<leader>cT", "<cmd>:%s/  /\\t/g<cr>", { desc = "Convert all spaces into tabs" })
map("n", "<leader>cW", "<cmd>:%s/\\s\\+$//e<cr>", { desc = "Trim all trailing whitespace" })

map("n", "<leader>ff", function() Snacks.picker.files() end, { desc = "Find Files (Root)" })
map("n", "<leader>fg", function() Snacks.picker.git_files() end, { desc = "Find Files (Git)" })
map("n", "<leader>fb", function() Snacks.picker.buffers() end, { desc = "Buffers" })
map("n", "<leader>fr", function() Snacks.picker.recent() end, { desc = "Recent Files" })
map("n", "<leader>fp", function() Snacks.picker.projects() end, { desc = "Projects" })

map("n", "<leader>fsg", function() Snacks.picker.grep() end, { desc = "Live Grep" })
map("n", "<leader>sr", "<cmd>Spectre<cr>", { desc = "Search & Replace" })
map("n", "<leader>fsw", "<cmd>Spectre open_file_cwd<cr>", { desc = "Search Current File" })

map("n", "<leader>gg", "<cmd>LazyGit<cr>", { desc = "LazyGit" })
map("n", "<leader>gd", function() Snacks.picker.git_diff() end, { desc = "Git Diff (Hunks)" })
map("n", "<leader>gc", function() Snacks.picker.git_log() end, { desc = "Commits" })

map("n", "<leader>ghu", "<cmd>Gitsigns undo_stage_hunk<cr>", { desc = "Undo Stage" })
map("n", "<leader>ghn", "<cmd>Gitsigns next_hunk<cr>", { desc = "Next Hunk" })
map("n", "<leader>ghN", "<cmd>Gitsigns prev_hunk<cr>", { desc = "Prev Hunk" })
map("n", "<leader>ghc", "<cmd>Gitsigns preview_hunk<cr>", { desc = "Preview Hunk" })
map("n", "<leader>ghr", "<cmd>Gitsigns reset_hunk<cr>", { desc = "Reset Hunk" })
map("n", "<leader>ghR", "<cmd>Gitsigns reset_buffer<cr>", { desc = "Reset Buffer" })
map("n", "<leader>ghl", "<cmd>Gitsigns blame_line<cr>", { desc = "Blame Line" })
map("n", "<leader>ghd", "<cmd>Gitsigns diffthis<cr>", { desc = "Diff This" })
map("n", "<leader>ghs", "<cmd>Gitsigns select_hunk<cr>", { desc = "Select Hunk" })

map("n", "<leader>ter", "<cmd>lua require('neotest').run.run()<cr>", { desc = "Run Test" })
map("n", "<leader>tef", "<cmd>lua require('neotest').run.run(vim.fn.expand('%'))<cr>", { desc = "Run File Tests" })
map("n", "<leader>ted", "<cmd>lua require('neotest').run.run({strategy = 'dap'})<cr>", { desc = "Debug Test" })
map("n", "<leader>tes", "<cmd>lua require('neotest').summary.toggle()<cr>", { desc = "Test Summary" })
map("n", "<leader>teo", "<cmd>lua require('neotest').output.open({ enter = true })<cr>", { desc = "Test Output" })



map("t", "<Esc>", "<C-\\><C-n>", { desc = "Exit Terminal Mode" })
map({ "n", "t" }, "<C-\\>", function() Snacks.terminal.toggle() end, { desc = "Toggle Terminal" })

map("n", "<leader>uu", function() Snacks.picker.undo() end, { desc = "Undo History" })

map("n", "<leader>kk", function() Snacks.picker.keymaps() end, { desc = "Show Keymaps" })

map("n", "<leader><space>", function() Snacks.picker.smart() end, { desc = "Smart Find Files" })
map("n", "<leader>,", function() Snacks.picker.buffers() end, { desc = "Buffers" })
map("n", "<leader>/", function() Snacks.picker.grep() end, { desc = "Grep" })
map("n", "<leader>:", function() Snacks.picker.command_history() end, { desc = "Command History" })
map("n", "<leader>n", function() Snacks.picker.notifications() end, { desc = "Notification History" })
map("n", "<leader>e", function() Snacks.explorer() end, { desc = "File Explorer" })

map("n", "<leader>fc", function() Snacks.picker.files({ cwd = vim.fn.stdpath("config") }) end, { desc = "Find Config File" })
map("n", "<leader>fe", function() Snacks.explorer() end, { desc = "File Tree" })

map("n", "<leader>oio", "<cmd>OpencodeInputOpen<cr>", { desc = "Open Input" })
map("n", "<leader>oin", "<cmd>OpencodeInputNew<cr>", { desc = "New Session" })
map("n", "<leader>ooo", "<cmd>OpencodeOutputOpen<cr>", { desc = "Open Output" })
map("n", "<leader>oss", "<cmd>OpencodeSessionSelect<cr>", { desc = "Select Session" })
map("n", "<leader>osr", "<cmd>OpencodeSessionRename<cr>", { desc = "Rename Session" })
map("n", "<leader>og", "<cmd>OpencodeToggle<cr>", { desc = "Toggle" })
map("n", "<leader>oq", "<cmd>OpencodeClose<cr>", { desc = "Close" })
map("n", "<leader>o/", "<cmd>OpencodeQuickChat<cr>", { desc = "Quick Chat" })
map("n", "<leader>odo", "<cmd>OpencodeDiffOpen<cr>", { desc = "Open Diff" })
map("n", "<leader>od]", "<cmd>OpencodeDiffNext<cr>", { desc = "Next Diff" })
map("n", "<leader>od[", "<cmd>OpencodeDiffPrev<cr>", { desc = "Prev Diff" })
map("n", "<leader>odc", "<cmd>OpencodeDiffClose<cr>", { desc = "Close Diff" })
map("n", "<leader>odx", "<cmd>OpencodeDiffSwap<cr>", { desc = "Swap Position" })
map("n", "<leader>op", "<cmd>OpencodeConfigureProvider<cr>", { desc = "Configure Provider" })
map("n", "<leader>oz", "<cmd>OpencodeToggleZoom<cr>", { desc = "Toggle Zoom" })

map("n", "<leader>gf", function() Snacks.picker.git_log_file() end, { desc = "Git Log File" })
map("n", "<leader>gb", function() Snacks.picker.git_branches() end, { desc = "Git Branches" })
map("n", "<leader>gs", function() Snacks.picker.git_status() end, { desc = "Git Status" })
map("n", "<leader>gS", function() Snacks.picker.git_stash() end, { desc = "Git Stash" })
map("n", "<leader>gl", function() Snacks.picker.git_log() end, { desc = "Git Log" })
map("n", "<leader>gL", function() Snacks.picker.git_log_line() end, { desc = "Git Log Line" })
map("n", "<leader>gi", function() Snacks.picker.gh_issue() end, { desc = "GitHub Issues (open)" })
map("n", "<leader>gI", function() Snacks.picker.gh_issue({ state = "all" }) end, { desc = "GitHub Issues (all)" })
map("n", "<leader>gp", function() Snacks.picker.gh_pr() end, { desc = "GitHub PRs (open)" })
map("n", "<leader>gP", function() Snacks.picker.gh_pr({ state = "all" }) end, { desc = "GitHub PRs (all)" })

map("n", '<leader>s"', function() Snacks.picker.registers() end, { desc = "Registers" })
map("n", '<leader>s/', function() Snacks.picker.search_history() end, { desc = "Search History" })
map("n", "<leader>sa", function() Snacks.picker.autocmds() end, { desc = "Autocmds" })
map("n", "<leader>sb", function() Snacks.picker.lines() end, { desc = "Buffer Lines" })
map("n", "<leader>sB", function() Snacks.picker.grep_buffers() end, { desc = "Grep Open Buffers" })
map("n", "<leader>sc", function() Snacks.picker.command_history() end, { desc = "Command History" })
map("n", "<leader>sC", function() Snacks.picker.commands() end, { desc = "Commands" })
map("n", "<leader>sh", function() Snacks.picker.help() end, { desc = "Help Pages" })
map("n", "<leader>sH", function() Snacks.picker.highlights() end, { desc = "Highlights" })
map("n", "<leader>si", function() Snacks.picker.icons() end, { desc = "Icons" })
map("n", "<leader>sj", function() Snacks.picker.jumps() end, { desc = "Jumps" })
map("n", "<leader>sk", function() Snacks.picker.keymaps() end, { desc = "Keymaps" })
map("n", "<leader>sl", function() Snacks.picker.loclist() end, { desc = "Location List" })
map("n", "<leader>sm", function() Snacks.picker.marks() end, { desc = "Marks" })
map("n", "<leader>sM", function() Snacks.picker.man() end, { desc = "Man Pages" })
map("n", "<leader>sp", function() Snacks.picker.lazy() end, { desc = "Lazy Plugin Search" })
map("n", "<leader>sq", function() Snacks.picker.qflist() end, { desc = "Quickfix List" })
map("n", "<leader>sR", function() Snacks.picker.resume() end, { desc = "Resume Picker" })
map("n", "<leader>sg", function() Snacks.picker.grep() end, { desc = "Grep" })
map({ "n", "x" }, "<leader>sw", function() Snacks.picker.grep_word() end, { desc = "Grep Word/Selection" })

map({ "n", "x" }, "gx", function()
  vim.api.nvim_command('call netrw#BrowseX(expand((exists("g:netrw_gx")? g:netrw_gx : ""), mode() == "x" ? "<cfile>" : "<cfile>"), netrw#CheckIfRemote(expand((exists("g:netrw_gx")? g:netrw_gx : ""), mode() == "x" ? "<cfile>" : "<cfile>")))')
end, { desc = "Open with System App" })

map("n", "<leader>ha", function() Snacks.picker.bookmarks.add() end, { desc = "Add Bookmark" })
map("n", "<leader>hr", function() Snacks.picker.bookmarks.remove() end, { desc = "Remove Bookmark" })
map("n", "<leader>hh", function() Snacks.picker.bookmarks() end, { desc = "Bookmarks" })
map("n", "<leader>ht", function() Snacks.picker.recent() end, { desc = "Recent Files" })

map("n", "<leader>ca", vim.lsp.buf.code_action, { desc = "Code Action" })
map("n", "<leader>cr", vim.lsp.buf.rename, { desc = "Rename" })
map("n", "<leader>cf", function() vim.lsp.buf.format { async = true } end, { desc = "Format" })

map("n", "<leader>tt", function() Snacks.terminal.toggle() end, { desc = "Toggle Terminal" })

map("n", "<leader>ld", function() Snacks.picker.lsp_definitions() end, { desc = "Go to Definition" })
map("n", "<leader>lg", function() Snacks.picker.lsp_declarations() end, { desc = "Go to Declaration" })
map("n", "<leader>lr", function() Snacks.picker.lsp_references() end, { nowait = true, desc = "Go to References" })
map("n", "<leader>li", function() Snacks.picker.lsp_implementations() end, { desc = "Go to Implementation" })
map("n", "<leader>lt", function() Snacks.picker.lsp_type_definitions() end, { desc = "Go to Type Definition" })
map("n", "<leader>ls", function() Snacks.picker.lsp_symbols() end, { desc = "LSP Symbols" })
map("n", "<leader>lS", function() Snacks.picker.lsp_workspace_symbols() end, { desc = "LSP Workspace Symbols" })
map("n", "<leader>lci", function() Snacks.picker.lsp_incoming_calls() end, { desc = "Calls Incoming" })
map("n", "<leader>lco", function() Snacks.picker.lsp_outgoing_calls() end, { desc = "Calls Outgoing" })
map("n", "<leader>lh", vim.lsp.buf.signature_help, { desc = "Signature Help" })
map("n", "<leader>lk", vim.lsp.buf.hover, { desc = "Hover Doc" })
map("n", "<leader>lq", vim.diagnostic.setloclist, { desc = "Diagnostics to Loclist" })

map("n", "zM", "zM", { desc = "Fold All" })
map("n", "zR", "zR", { desc = "Unfold All" })
map("n", "z0", "z0", { desc = "Fold Level 0 (None)" })
map("n", "z1", "z1", { desc = "Fold Level 1" })
map("n", "z2", "z2", { desc = "Fold Level 2" })
map("n", "z3", "z3", { desc = "Fold Level 3" })

map("n", "<leader>xq", "<cmd>copen<cr>", { desc = "Open Quickfix" })
map("n", "<leader>xl", "<cmd>lopen<cr>", { desc = "Open Loclist" })


map("n", "<leader>wh", "<C-w>h", { desc = "Left Window", remap = true })
map("n", "<leader>wj", "<C-w>j", { desc = "Lower Window", remap = true })
map("n", "<leader>wk", "<C-w>k", { desc = "Upper Window", remap = true })
map("n", "<leader>wl", "<C-w>l", { desc = "Right Window", remap = true })
map("n", "<leader>wH", "<cmd>resize +2<cr>", { desc = "Increase Height" })
map("n", "<leader>wJ", "<cmd>resize -2<cr>", { desc = "Decrease Height" })
map("n", "<leader>wK", "<cmd>vertical resize +2<cr>", { desc = "Increase Width" })
map("n", "<leader>wL", "<cmd>vertical resize -2<cr>", { desc = "Decrease Width" })

map("n", "[q", "<cmd>cprev<cr>", { desc = "Previous quickfix" })
map("n", "]q", "<cmd>cnext<cr>", { desc = "Next quickfix" })
map("n", "[Q", "<cmd>cfirst<cr>", { desc = "First quickfix" })
map("n", "]Q", "<cmd>clast<cr>", { desc = "Last quickfix" })

map("n", "<leader>bn", "<cmd>bn<cr>", { desc = "Next Buffer" })
map("n", "<leader>bp", "<cmd>bp<cr>", { desc = "Previous Buffer" })
map("n", "<leader>bd", "<cmd>Bdelete<cr>", { desc = "Delete Buffer" })

map("n", "<leader>kh", function() Snacks.picker.help() end, { desc = "Help" })

map("n", "<leader>qq", "<cmd>qa<cr>", { desc = "Quit All" })
map("n", "<leader>qs", function() vim.cmd("mksession! " .. vim.fn.stdpath("data") .. "/sessions/session.vim") end, { desc = "Save Session" })
map("n", "<leader>ql", function() vim.cmd("source " .. vim.fn.stdpath("data") .. "/sessions/session.vim") end, { desc = "Load Session" })
map("n", "<leader>qd", function() vim.fn.delete(vim.fn.stdpath("data") .. "/sessions/session.vim") end, { desc = "Delete Session" })

map("n", "<leader>vc", function() Snacks.picker.colorschemes() end, { desc = "Colorscheme" })

map("n", "<leader>ton", "<cmd>set number!<cr>", { desc = "Toggle Line Numbers" })
map("n", "<leader>tow", "<cmd>set wrap!<cr>", { desc = "Toggle Line Wrap" })
map("n", "<leader>tos", "<cmd>set spell!<cr>", { desc = "Toggle Spell Check" })
map("n", "<leader>toz", function() vim.diagnostic.enable(not vim.diagnostic.is_enabled()) end, { desc = "Toggle Diagnostics" })
map("n", "<leader>ti", "<cmd>IBLToggle<cr>", { desc = "Toggle Indent Guides" })
map("n", "<leader>tc", "<cmd>set cursorline!<cr>", { desc = "Toggle Cursor Line" })
map("n", "<leader>ts", function() vim.o.signcolumn = vim.o.signcolumn == "yes" and "no" or "yes" end, { desc = "Toggle Sign Column" })
map("n", "<leader>tr", "<cmd>set relativenumber!<cr>", { desc = "Toggle Relative Numbers" })

map("n", "<leader><tab>n", "<cmd>tabnew<cr>", { desc = "New Tab" })
map("n", "<leader><tab>c", "<cmd>tabclose<cr>", { desc = "Close Tab" })
map("n", "<leader><tab>]", "<cmd>tabnext<cr>", { desc = "Next Tab" })
map("n", "<leader><tab>[", "<cmd>tabprevious<cr>", { desc = "Previous Tab" })
map("n", "<leader><tab>l", "<cmd>tablast<cr>", { desc = "Last Tab" })
map("n", "<leader><tab>f", "<cmd>tabfirst<cr>", { desc = "First Tab" })
