return {
  -- themes
  "sainnhe/sonokai",
  "tiagovla/tokyodark.nvim",
  "projekt0n/github-nvim-theme",
  "olimorris/onedarkpro.nvim",
  "miikanissi/modus-themes.nvim",
  "rmehri01/onenord.nvim",
  { "catppuccin/nvim",            name = "catppuccin" },
  { "ahmedabdulrahman/aylin.vim", branch = "0.5-nvim" },
  "rebelot/kanagawa.nvim",
  "NLKNguyen/papercolor-theme",
  "sainnhe/edge",
  "nyoom-engineering/oxocarbon.nvim",
  "AlexvZyl/nordic.nvim",
  "kaicataldo/material.vim",
  "neanias/everforest-nvim",

  -- basics
  "kyazdani42/nvim-web-devicons",
  "nvim-lua/plenary.nvim",
  "MunifTanjim/nui.nvim",
  "akinsho/bufferline.nvim",
  "moll/vim-bbye",
  "3rd/image.nvim",
  {
    "folke/noice.nvim",
    event = "VeryLazy",
    dependencies = {
      "MunifTanjim/nui.nvim",
      "rcarriga/nvim-notify",
    }
  },
  {
    "nvim-neo-tree/neo-tree.nvim",
    branch = "v3.x",
    cmd = "Neotree",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-tree/nvim-web-devicons",
      "MunifTanjim/nui.nvim",
      "3rd/image.nvim",
    }
  },

  -- LSP & completion
  "williamboman/mason.nvim",
  { "williamboman/mason-lspconfig.nvim", dependencies = { "mason.nvim" } },
  "neovim/nvim-lspconfig",
  "nvimdev/lspsaga.nvim",
  "hrsh7th/cmp-nvim-lsp",
  "hrsh7th/cmp-buffer",
  "hrsh7th/cmp-path",
  "hrsh7th/cmp-cmdline",
  "hrsh7th/nvim-cmp",
  "L3MON4D3/LuaSnip",
  "nvim-treesitter/nvim-treesitter",
  "nvim-treesitter/nvim-treesitter-textobjects",
  "dnlhc/glance.nvim",
  "tamago324/nlsp-settings.nvim",
  "folke/trouble.nvim",
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    init = function()
      vim.o.timeout = true
      vim.o.timeoutlen = 500
    end,
  },
  "nvim-lualine/lualine.nvim",
  "akinsho/toggleterm.nvim",
  "lewis6991/gitsigns.nvim",
  "BurntSushi/ripgrep",
  "nvim-telescope/telescope.nvim",
  { "kdheepak/lazygit.nvim", dependencies = { "nvim-lua/plenary.nvim" } },
  "numToStr/Comment.nvim",
  "rafamadriz/friendly-snippets",
  "saadparwaiz1/cmp_luasnip",
  "echasnovski/mini.pairs",
  "echasnovski/mini.ai",
  "echasnovski/mini.hipatterns",
  "echasnovski/mini.indentscope",
  "echasnovski/mini.surround",
  "stevearc/conform.nvim",
  "mfussenegger/nvim-lint",
  "nvim-telescope/telescope-frecency.nvim",
  "debugloop/telescope-undo.nvim",
  "nvim-pack/nvim-spectre",
  "ThePrimeagen/harpoon",
  "lukas-reineke/indent-blankline.nvim",
  "RRethy/vim-illuminate",
  "norcalli/nvim-colorizer.lua",
  "max397574/better-escape.nvim",
  "olimorris/persisted.nvim",
  "ahmedkhalf/project.nvim",
  "nvim-neotest/nvim-nio",
  "nvim-neotest/neotest",
  "sindrets/diffview.nvim",
  "akinsho/git-conflict.nvim",
  "nvim-neotest/neotest-python",

  -- python
  { "linux-cultist/venv-selector.nvim" },
}
